name = "5wordle.com"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
NEXTAUTH_URL = "https://5wordle.com"
NEXTAUTH_SECRET = "your-secret-key"